### ISSUE TITLE
Unable to utilise in the context of Babylon JS

### ISSUE THREAD

**Issue by lachlanphillips** [sebavan/BabylonjsAnimatedGifSample#12]
Hi, I'm having trouble with seeing how this can be utilised in the context of BabylonJS. It seems like there's only one .js file, which is index.js. It's missing from this repo, and I had to get it from the demo elsewhere. It's also minified, and doesn't appear to extend Babylon.js, but replaces it entirely. 

Am i missing something? Is this intended to be used in the context of Babylon.js or is this a standalone tech demo?

Thanks

**Comment by sebavan** [comment]
It is intended to be used as a source in your project from the blog: **https://babylonjs.medium.com/animated-gifs-in-webgl-55a6c7bc9c93** You can add and tweak the source as will, it is a demo project.

It is not intended to be used directly.
